server:
  port: 80
  servlet:
    contextPath: /api

spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: 27017
      database: quiztgbot
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

bot:
  BOT_NAME: ENC(z1ppwOIhTdvL3T1A/iS1nW2o2WJwgCr4d4UpdPPKC3A=)
  BOT_TOKEN: ENC(j5E2zkdWb+tlyvYgeSSHCmnYnDlxr0lirIiuIS6eV7r7GLQB4cC7pkJ2WVydte7mDlALXeyT5aw=)
  time-limit-enabled: true
